spring.application.name=spellingforammo

# --- DataSource ---
spring.datasource.url=jdbc:postgresql://localhost:5432/ammoworddb
spring.datasource.username=app
spring.datasource.password=secret
spring.flyway.enabled=false

# spring.datasource.driver-class-name=org.postgresql.Driver  # optional; Boot detects it

# --- JPA/Hibernate ---
#spring.jpa.hibernate.ddl-auto=update     # dev convenience; prefer Flyway for prod
spring.jpa.properties.hibernate.default_schema=app
#change this after the initial back to update
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false

# --- Hikari (optional but helpful) ---
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.initializationFailTimeout=0


# H2 Database settings
#spring.datasource.url=jdbc:h2:file:./ammo_db
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=

# JPA
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# H2 console (web access)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

server.address=0.0.0.0
server.port=8080

